
#pragma config(Sensor, in1,    lefts,          sensorPotentiometer)
#pragma config(Sensor, in2,    fronts,         sensorPotentiometer)
#pragma config(Sensor, in3,    rights,         sensorPotentiometer)
#pragma config(Sensor, in4,    backs,          sensorPotentiometer)
#pragma config(Motor,  port1,           middle,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           front,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           back,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           catapult,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//start with aunton code://////////////////////////////////////////////////////////////////////////

#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
int selectedAutonomous = 2;

//an integer to track potentiometer rotations
int rot = 0;

//preaunton
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

}

task autonomous()
{
	//aunton code here
	while (rot < 3){ // repeat this many full potentiometer rotations

  	SensorValue[lefts] = 0;

		while(SensorValue[lefts] < 4095) {
			motor[left] = 127;
	 		motor[right] = 127;
	 	}
	 	rot = rot + 1;

	}

}

//set up motors ^

task middlewheel(){
	if (vexRT[Btn7L] == 1){

		if (motor[middle] > 100){ //if motor spining, stop it
			motor[middle] = 0;
		}

		if (motor[middle] < 100){ //if not spinig, start spining
			motor[middle] = 127;
		}

	}
}



task usercontrol()
{

	//repeat forever
	while(1 == 1)
	{
		//call on the other task to start the middle motor spinning at all times until stopped
    startTask (middlewheel);


	  //these say "move (straif) the motor according to the position of the joysticks"

		motor[back] = -vexRT[Ch2];
		motor[right] = -vexRT[Ch1];
		motor[front] = vexRT[Ch2];
		motor[left] = vexRT[Ch1];

		//rotate when I press the topright buttons
		if (vexRT[Btn6U] == 1){
			motor[back] = 127;
		   motor[right] = 127;
	  	   motor[front] = 127;
	    	motor[left] = 127;
		}

		if (vexRT[Btn6D] == 1){
			motor[back] = -127;
		    motor[right] = -127;
	  	    motor[front] = -127;
	  	    motor[left] = -127;
		}

		//intake controls:
		if (vexRT[Btn7U] == 1){
			motor[intake] = 127;
	  }
	  if (vexRT[Btn7D] == 1){
	  	motor[intake] = -127;
	  }

	  //catapult code:
	  if (vexRT[Btn7R] == 1){
	  	motor[catapult] = 127;
	  }

		//if no buttons pressed, do nothing
		else{
			//ooooooo ahahahahahahhahahahahhahahahahhahahahahha
		  motor[catapult] = 0;
		  motor[intake] = 0;
		  motor[back] = 0;
		  motor[right] = 0;
	  	  motor[front] = 0;
	  	  motor[left] = 0;
		}



	}


}
